### ISSUE TITLE
Problems building from tarball

### ISSUE THREAD

**Issue by goodsman** [thk686/odeintr#2]
Because of recent changes to the package, I have opted to build the package from its tarball in Rstudio running Windows 7. Two issues arise.

The first issue when checking the package is that roxygen2 is not available for R version 3.2.2.

The second issue arises when attempting to build the package and reload it, the check comes up with two problems, both of which are in the unused.hpp header file:
-on line 57: "this" is not a potential constant expression
-on line 67: both 'const' and 'constexpr' cannot be used here

Any insight into this?

**Comment by goodsman** [comment]
It seems that was the first issue above was my own mistake. However to build from tarball, the user must install roxygen2 and knitr themselves.

**Comment by thk686** [comment]
I expect that is right. I will see if they need to be added to the deps.

THK

http://www.keittlab.org/

**Comment by thk686** [comment]
http://www.keittlab.org/

On Wed, Sep 23, 2015 at 12:16 PM, goodsman notifications@github.com wrote:

> Because of recent changes to the package, I have opted to build the
> package from its tarball in Rstudio running Windows 7. Two issues arise.
> 
> The first issue when checking the package is that roxygen2 is not
> available for R version 3.2.2.
> 
> You should not need roxygen2 as the git repo has the help files pre-built,
> ie, I run roxygen2 before pushing to the repo. If you are building from
> within RStudio, you need to tell it not to call roxygen2.
> 
> The second issue arises when attempting to build the package and reload
> it, the check comes up with two problems, both of which are in the
> unused.hpp header file:
> -on line 57: "this" is not a potential constant expression
> -on line 67: both 'const' and 'constexpr' cannot be used here
> 
> Any insight into this?

Which version of gcc? I think you need 4.8 to compile Boost Fusion, which
is a dependency of Boost ODEINT.

**Comment by thk686** [comment]
I can confirm that g++ 4.6.x does not work with the version of Boost libraries supplied by the BH R package. I had to hack my TravisCI setup to install g++ 4.8.x to get it to build. So I suspect this will not work with Windows until RTools is updated to g++ >= 4.8. The very latest RTools uses g++ 4.9.x, so there is some hope. I don't think it is released yet however.

**Comment by thk686** [comment]
Could you try RTools 3.3 and let me know if it works?

**Comment by goodsman** [comment]
Even with the new version of RTools (3.3), I have been unable to build from
the tarball.

On Fri, Sep 25, 2015 at 9:13 AM, Tim Keitt notifications@github.com wrote:

> Could you try RTools 3.3 and let me know if it works?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/thk686/odeintr/issues/2#issuecomment-143248950.

## 

Devin W. Goodsman
Postdoctoral Researcher
Spatial Ecology and Entomology
University of Alberta

**Comment by thk686** [comment]
I think it v3.3 has both 4.6 and 4.9 versions of g++. I don't know how to
select the one that is used.

**Comment by thk686** [comment]
I now include the necessary Boost libraries along with odeintr. It now compiles under g++ 4.6 and so should work with windows.
